### PR TITLE
slovak translations

### PR DESCRIPTION
**Pull request by michalrusina**

### CODE REVIEW

**Comment by n-kb** [comment]
@michalrusina amazing work! Don't hesitate to credit yourself on the home page of the SK version. You can also change the shared image in `sk.json` and possibly the canonical share URL, so that it leads to the page at dennikn.sk where you'll put it.

**Comment by michalrusina** [comment]
@n-kb Hi. So the preffered way of embedding is to create a copy and host it? Is it ok to change the background images on our hosted copy (Slovak cities for instance)? Also, wil there be a link to the slovak version here pon github?

**Comment by n-kb** [comment]
@michalrusina Sure, feel free to copy and host directly and to change the images (we used Prisma filters on all pictures). We'll add the link to the SK version when it's live.

**Comment by michalrusina** [comment]
@n-kb hi, is there a way to start the game in a chosen language? even if i open the file sk.html, i get the english translation...

**Comment by n-kb** [comment]
@michalrusina Once in production, there's a page for each language, e.g: https://jplusplus.github.io/the-accountant/fr.html#/

**Comment by michalrusina** [comment]
@n-kb i tried to make the production build locally, it creates the sk.html page but the language is in english

**Comment by n-kb** [comment]
@michalrusina Did you pull this commit ?

https://github.com/jplusplus/the-accountant/commit/b3542e83e0396667fa73294fb876a750cf497b43

**Pull request merged**
